name: Deploy

on: [workflow_dispatch, push, pull_request]

env:
  SERVER_HOST: ${{ secrets.SERVER_IP }}
  SERVER_USER: root
  SERVER_PATH: /var/www/fitnessplus
  
jobs:
  deploy:
    name: Deploy and Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      # Setup key
      - run: set -eu
      - run: mkdir "$HOME/.ssh"
      - run: echo "${{ secrets.ACTION_KEY }}" > "$HOME/.ssh/key"
      - run: chmod 600 "$HOME/.ssh/key"
      # Add .env
      - run: echo "VITE_API = ${{ secrets.API_URL }}" > ".env"
      # Build
      - run: npm i
      - run: npm run build
      # Deploy
      - run: rsync -e "ssh -i $HOME/.ssh/key -o StrictHostKeyChecking=no" --archive --compress --delete . ${{ env.SERVER_USER }}@${{ env.SERVER_HOST }}:${{ env.SERVER_PATH }}
     
